<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="home" failures="1" tests="4" name="Testlockout" time="8.578" errors="0" timestamp="2023-09-03T01:17:44 EDT">
  <testcase classname="com.agile.saucedemo.testsScript.TestngClass2" name="userLogin2" time="0.125"/>
  <testcase classname="com.agile.saucedemo.testsScript.TestngClass2" name="password2" time="0.037"/>
  <testcase classname="com.agile.saucedemo.testsScript.TestngClass2" name="loginInp3" time="0.246"/>
  <testcase classname="com.agile.saucedemo.testsScript.TestngClass2" name="tearDown" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at com.agile.saucedemo.testsScript.TestngClass2.tearDown(TestngClass2.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- tearDown -->
</testsuite> <!-- Testlockout -->
